### ISSUE TITLE
2020/5/31

### ISSUE THREAD

**Issue by aki19930119** [aki19930119/StripeAppSample#1]
CustomerIDが取れていない？

**Comment by fusso** [comment]
ViewController s.36

> let customerId = "firestoreから取得"

ここに対応するcustomerIdが入ってないといけない？

**Comment by fusso** [comment]
https://qiita.com/k-boy/items/c99cc681c29a1b250b4a#%E9%A1%A7%E5%AE%A2%E3%81%AE%E4%BD%9C%E6%88%90

> FirebaseのAuthでユーザーを作成し、そこで得たemailアドレスを使って先ほどのAPIを叩きcustomerIdを取得、最後に細かいプロフィール情報は、FireStoreのUsersというcollectionに格納、その中のパラメータの１つとしてcustomerIdを作って入れるという手順

createStripeCustomerのAPIを呼び出しているこの関数は呼び出されている？

**Comment by aki19930119** [comment]
Error Domain=com.firebase.functions Code=5 "NOT FOUND" UserInfo={NSLocalizedDescription=NOT FOUND}

エラー内容

**Comment by aki19930119** [comment]
Bundle ID : set same with Xcode project and GoogleService-Info.plist

Set IdenpotencyKey to Create Ephemeralkey API

Set Stripe SecretKey

**Comment by aki19930119** [comment]
firebase Bradeにしてなかったためstripeのapiが呼び出せなかった
